name: appointment
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/calendar.png"
flutter:
  uses-material-design: true
  assets:
    - assets/bone.png
    - assets/brain.png
    - assets/aliTurker.jpg
    - assets/baharSezer.jpg
    - assets/heart.png
    - assets/profile_img.png
    - assets/tooth.png
    - assets/muratAziz.png
    - assets/onurUstunel.jpeg
    - assets/doctorIcon.png